### ISSUE TITLE
Generalized PV model interface

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#102]
Currently `rdtools.normalization` uses wrappers for some specific pvlib models. To maintain a clean, interoperable ecosystem for PV modeling and analysis, it would make sense to enable RdTools to work more generally with arbitrary models from pvlib. It seems to me that the logical way to achieve this is to develop normalization functions that take pvlib `ModelChain` objects as an input.

@wholmgren and @cwhanse, I'm interested to hear any thoughts (or warnings) you have at the outset.

**Comment by cwhanse** [comment]
@mdeceglie are you referring, for example, to `rdtools.normalization.sapm_dc_power`? This function operates on a `pvlib` `LocalizedPVSystem` object, and performs a sequence of `pvlib.PVSystem` object methods (solar position, POA, cell temp, DC output). In that sense the `rdtools` function is doing what `ModelChain` object was designed for. It may be that `ModelChain` isn't as flexible as `rdtools` may want, since most of the development of `ModelChain` was motivated by making the modeling sequence convenient.

**Comment by mdeceglie** [comment]
Considering the example of `rdtools.normalization.sapm_dc_power`, it implements a specific model. I'm interested in providing users the opportunity to specify arbitrary models to serve as the basis for normalization and subsequent analysis. Perhaps it's best to develop a prototype for what I'm thinking to help fuel discussion, but I wanted to see if there were any show stoppers I'm missing.

**Comment by wholmgren** [comment]
I agree that it sounds a lot like what `ModelChain` was designed for but flexibility could be a concern. Let us know if you run into issues. I'm not that familiar with `rdtools` but it looks like `normalize_with_sapm(energy, sapm_kws)` could be `normalize_with_modelchain(energy, mc)` without too much effort.

A little off topic, but I think `LocalizedPVSystem` was a mistake, so use with caution.

**Comment by mdeceglie** [comment]
To lay the groundwork for this (or potentially even close the issue), we should probably refactor `normalization.py` such that the there is a function which accepts measured and modeled PV, on potentially different time axes, and performs the normalization. Currently this logic is buried in each of the specific normalization functions.
