### ISSUE TITLE
heads up: issues reproducing clearsky results (again) with new pvlib

### ISSUE THREAD

**Issue by computron** [NREL/rdtools#106]
Hi,

I am again having trouble reproducing the results in:
https://github.com/NREL/rdtools/blob/master/docs/degradation_example.ipynb

with the latest pvlib.

* If I use rdtools to install pvlib (using rdtools requirements), then there is no issue. The online example and my local example match.
* If I install pvlib myself first (I tried both bleeding edge github as well as v0.6.0-alpha), I get very different results (see screenshot below).

<img width="651" alt="screen shot 2018-11-24 at 7 29 08 am" src="https://user-images.githubusercontent.com/986759/48968970-d3bbf200-efbc-11e8-932d-194b860b1caf.png">

I know rdtools requirements is that pvlib should be between 0.5 and 0.6, so perhaps my manual pvlib installation was out of bounds from those requirements. But I did want to give a heads up that upgrading pvlib to the latest version changes the results on the notebook significantly.

For now, I will work using the "rdtools-only" installation which appears to install pvlib v0.5.2 and gives the same results as the online notebook.

**Comment by mdeceglie** [comment]
@computron Thank you for the heads up. pvlib introduced some API changes in 0.6.0 which is why we specify `'pvlib >= 0.5.0, <0.6.0'`, as you've pointed out. I will close this issue in favor of #97.

We tracked this down to a change in the default behavior of `pvlib.clearsky.ineichen()`. Here's the relevant expert from the [pvlib 0.6.0 What's new page](https://pvlib-python.readthedocs.io/en/v0.6.0/whatsnew.html)  

> Add perez_enhancement keyword argument to clearsky.ineichen to control whether or not the “perez enhancement factor” is applied. The enhancement factor was always applied until now. Now it is turned off by default. 

For versions of pvlib >= 0.6.0, using `clearsky = loc.get_clearsky(df.index, solar_position = sun, perez_enhancement=True)` in the first step of the clear sky workflow in the RdTools example notebook recovers the clear sky result shown in the master branch version of the RdTools example in v1.2.0. (In my testing at least, please let us know if you find that it doesn't!).

**Comment by wholmgren** [comment]
Hi folks, from the pvlib perspective, I am wondering why you feel like this is an issue that merits a version restriction. The "perez enhancement" is unquestionably problematic for some inputs. I'd like to understand if we can improve the documentation or even change the default behavior if warranted.

**Comment by mdeceglie** [comment]
Thanks @wholmgren. It's not this issue alone that drives the version restriction. Rather we haven't had a chance to fully investigate how the changes in pvlib 0.6.0 impact RdTools (#97). 

Regarding the perez_enhancement keyword argument, the issue from our end is that the default behavior of loc.get_clearsky() has changed, which changes the result of our example as written. I'm in favor of the default behavior being safer, so I think you might the right call by changing the default behavior. But from our perspective we still need to avoid compliant environments from resulting in different answers with our supplied example. One way to soften the blow of a change in default behavior might be to raise a warning when perez_enhancement is not supplied that default behavior has changed. (It seems appropriate to phase a warning like that out in future versions.)
