### ISSUE TITLE
Add link to readthedocs to README.rd

### ISSUE THREAD

**Issue by cwhanse** [NREL/rdtools#147]
The RdTools homepage on GitHub doesn't have a link to the documentation but has two links to the examples. I'd suggest replacing this line:

`Full examples are worked out in the example notebooks in [rdtools/docs](./docs/degradation_example.ipynb).`

with

`Full documentation can be found at [readthedocs] (https://rdtools.readthedocs.io/en/latest/).`

If you agree, push a change to the Development branch?  There's lots of branches and the workflow for changes isn't clear to me. #122 is relevant.

**Comment by kanderso-nrel** [comment]
The master branch is only used for releases and is currently at RdTools 1.2.0.  The docs introduced in #122 are for the development branch and include changes added after the last release, so there isn't a version of RTD docs available for 1.2.0 that we can link to.  The README on the development branch does link to RTD (https://github.com/NREL/rdtools/tree/development) and will get merged to master for the next release, so this issue is already "fixed in development branch". 

Strictly speaking, maybe we shouldn't have set the RTD builds to be public yet since they don't reflect an existing RdTools release.  Won't be an issue for much longer though since the next release should be coming soon. 

> There's lots of branches and the workflow for changes isn't clear to me.

There's a lot going on right now for sure :) I believe the RdTools workflow is similar to [gitflow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) except we don't do release branches.  We're keeping track of the release to-do list here: https://github.com/NREL/rdtools/projects/2, hopefully that lends some order to the chaos.

**Comment by cwhanse** [comment]
Thanks for the explanation for the workflow, that helps greatly. 

I still suggest changing the README text, and point the link to https://rdtools.readthedocs.io/en/latest/index.html rather than to the subordinate page https://rdtools.readthedocs.io/en/latest/example.html

**Comment by kanderso-nrel** [comment]
> I still suggest changing the README text, and point the link to https://rdtools.readthedocs.io/en/latest/index.html rather than to the subordinate page https://rdtools.readthedocs.io/en/latest/example.html

At long last, #140 included this change.  When the next release is cut, I think we should also add the RTD link to the project description line like this:

![image](https://user-images.githubusercontent.com/57452607/79789929-33c8dc00-8308-11ea-99aa-31b1942a4dae.png)
