### ISSUE TITLE
Update example notebook for use with PVDAQ data

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#23]
@cdeline @dirkjordan, do you guys have a suggestion for a good PVDAQ system we can use for our example notebook?

**Comment by cdeline** [comment]
I think we’ve used ASE in the past (system 39).  Dirk?

Chris Deline
National Renewable Energy Laboratory
303-384-6359

**Comment by dirkjordan** [comment]
Yes, ASE would be good, but only from 2003 on, the data before are a mess.

**Comment by amnag** [comment]
Hi @mdeceglie, @cdeline and @dirkjordan, I added two ipynb notebooks to the ipynb_example branch - one for OTF Sanyo and another for ASE. The notebook for OTF Sanyo shows a negative degradation rate as expected. @mdeceglie, can you please try running the OTF Sanyo notebook by uncommenting 
#list_years = avail_year 
and commenting out the line
list_years = [2011,2012,2013,2014] ?
These lines occur in input cell 9.
I tried running it, but it is taking too much time and running it using the NREL internet might be faster.

Although @dirkjordan mentioned data for ASE before May 2003 should not be used, the pvdaq-api for the annual csv  data  allows access to ASE data only unto 2003. However, I cannot use direct pvdaq access for multiple years because it crashes and hence have used data for ASE from 2000 to 2003 as a prototype for the ASE notebook. This is probably why I do not get a negative degradation rate.

**Comment by cdeline** [comment]
I tracked this issue down to the way the ASE data was being mirrored into PVDAQ.  Only the aggregated data was mirrored, not the raw data.

**Comment by amnag** [comment]
@cdeline, @mdeceglie and @dirkjordan, I updated the example notebooks for ASE and OTF Sanyo along the files of the notebook for the Desert Knowledge Center. I have pushed the changes to the ipynb_example branch. Saving the data file as a pickle is not working, so I saved the data frame in hdf5 format. Your feedback is welcome.

**Comment by amnag** [comment]
@cdeline, can you please take a look at the degradation_example_clearsky.ipynb notebook in condition_filter branch ? I have separated the filters into several functions. If you are satisfied with these functions, I will move them to filter.py

**Comment by mdeceglie** [comment]
I will also plan to take a look. Thanks @amnag

**Comment by dirkjordan** [comment]
The ASE example notebook looks to be running excruciatingly slow for me.  I noticed that the data frame contains 256 columns, at least that's what it says. If so, that would explain the slowness. We really use only about 10 columns for the analysis. I would only make calls to the columns we really need for the analysis. We should also consider capping the number of years, after all it is only an example, maybe 2003 - 2016?
Do we need the infer frequency step for the example? It takes a long time again and may not be necessary since we know what it is. We could just say that at this point we would include an infer frequency step for unknown data sets. 
The filtering step should eliminate irradiance data above 1200W/m2, right now there are data points up to 2000W/m2 that are unphysical. 
Tref should be 25C or 45C in the normalization step. 
The degradation rate is too high but it could be that some of these previous steps when implemented would correct it. The Rd for this system should be around 0.2%/year.
Github allows storage of files up to 50MB. I'm wondering if we limit it to the absolute necessary columns like dc power, acpower (maybe), some Tmods and irradiance could the hdf5 file below 50MB? In that case we wouldn't have to step the new user through the data extraction; instead the file would be already there in the repo for use?

**Comment by amnag** [comment]
@dirkjordan, @mdeceglie and @cdeline, I have addressed most of these issues. Even after lowering the number of columns, the hdf5 files are hundreds of MB. So these files cannot be added to git, given the 100MB file size limit.
