### ISSUE TITLE
Flake8 has removal of --diff option

### ISSUE THREAD

**Issue by mdeceglie** [NREL/rdtools#351]
Flake8 6.0.0 removed the --diff option. We should figure out what that means for our flake8 github action. https://flake8.pycqa.org/en/latest/release-notes/6.0.0.html#backwards-incompatible-changes

**Comment by kanderso-nrel** [comment]
We used the diff approach so that we could potentially have non-compliant code as needed without the linter constantly complaining about it (https://github.com/NREL/rdtools/pull/231#issuecomment-724869620).  In the ~2 years since then we've apparently only added one style violation (which would be trivial to fix), so I'm not sure there's much value in continuing to check diffs instead of the complete codebase.  I'd say let's just run flake8 normally (`flake8 . --config=.flake8 --count --statistics --show-source`) and re-evaluate if the need for non-compliant code that can't be addressed with `noqa` ever arises.
