### ISSUE TITLE
different results when running example notebook

### ISSUE THREAD

**Issue by computron** [NREL/rdtools#92]
Hi

I'm just getting started with rdtools and trying to reproduce the results of the example notebook.

https://github.com/NREL/rdtools/blob/master/docs/degradation_example.ipynb

The notebook seems to run fine (apart from needing to install the ``tables`` library, already pointed out in https://github.com/NREL/rdtools/issues/86, but easy to fix).

However, despite running smoothly, I am getting quite different results than what's listed online. See attachment at bottom for what I'm getting.

Any thoughts on why this might be? I want to make sure everything is being done correctly before trying this on new data sets.

Some notes:
- I am on Mac OS/X, Py 3.6.4
- I installed pvlib (today) by cloning the github repo, then running "python setup.py develop"
- I installed rdtools (today) by the same procedure

[notebook_executed.pdf](https://github.com/NREL/rdtools/files/2425218/notebook_executed.pdf)

**Comment by cdeline** [comment]
Confirmed - this has a root cause of the raw data download from DKCAS '84-Site_12-BP-Solar.csv' apparently having changed.  When I re-download the raw data, the sensor-based degradation drops from -0.75% / yr to -0.43%/yr, matching the above.  Clear-sky results are unchanged, so I suspect that an error in DKCAS'  measured ghi or dhi was found and now corrected.  Note the apparent drop in 2017 normalized energy that is no longer present.

![image](https://user-images.githubusercontent.com/23244088/46164987-a832ba80-c24c-11e8-9205-765de0adccfd.png)

![image](https://user-images.githubusercontent.com/23244088/46165167-3444e200-c24d-11e8-8ff8-deb33d0dc1b5.png)

**Comment by mdeceglie** [comment]
I also confirmed @cdeline's assessment of the change to the sensor based results: that the dataset has changed. For our next release I will rerun the notebook with a new version of the data and add a note about the discrepancy. 

@computron also has a discrepancy with his clear sky results. We tracked this down to a change in the default behavior of `pvlib.clearsky.ineichen()`. (https://github.com/pvlib/pvlib-python/pull/459 ) Using `clearsky = loc.get_clearsky(df.index, solar_position = sun, perez_enhancement=True)` in the first step of the clear sky workflow in the RdTools example notebook recovers the clear sky result shown in the master branch version of the RdTools example in v1.2.0

**Comment by dirkjordan** [comment]
What if we use different data for the example(s)? I think Github repo size can be up to 100MB. We had talked about adding an additional example for tracked systems. The Mesa top system is a file size of ca. 6-7MB for 9 years of data (15min frequency). We could add the OTF HIT system as a fixed tilt system. Currently, the file size is 67MB (1min frequency). I think we could drastically reduce the size by downsampling it to 15min intervals, and we could also reduce the number of years. We add both files to the repo and are independent of any changes that my occur at the Desert Knowledge Center.

**Comment by mdeceglie** [comment]
I'm in favor of developing an example that uses data we control. Let's be sure to make sure that it is public data we are authorized to distribute. Instead of storing it directly on github, I would prefer to host it elsewhere. Perhaps we can just keep the data available at https://www.nrel.gov/pv/rdtools.html or we can give people instructions to download something from PVDAQ.

related to #23

**Comment by mdeceglie** [comment]
@cdeline @dirkjordan I've addressed this in PR #98. Would one of you please take a look and provide a review?
